# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches: [main, master] # default branch of the project

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: sbt/setup-sbt@v1
      
      - name: Checkout my fork of sbt-dependency-submission
        uses: actions/checkout@v4
        with:
          repository: dancewithheart/sbt-dependency-submission
          ref: fix-191-log-response
          path: .github/actions/sbt-dependency-submission
      
      - name: Sbt Dependency Submission
        uses: ./.github/actions/sbt-dependency-submission
